# Generated by Django 3.2.3 on 2021-06-08 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('userID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('xp', models.BigIntegerField(default=0)),
                ('promoted_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ('rank', '-promoted_date'),
            },
        ),
    ]
